### ISSUE TITLE
Register submit throws error

### ISSUE THREAD

**Issue by Legend-Dale** [JOBAA/amos-ss15-proj4#69] opened 2015-06-14 11:29 UTC
This error is thrown when pressing the submit button.

Whitelabel Error Page

This application has no explicit mapping for /error, so you are seeing this as a fallback.
Sun Jun 14 13:27:04 CEST 2015
There was an unexpected error (type=Internal Server Error, status=500).
could not execute statement; SQL [n/a]; constraint [UK_BFGJS3FEM0HMJHVIH80158X29]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement

**Comment by BujakiAttila** [comment] 2015-07-11 13:44
I have just tested this feature and it works fine for me.

![image](https://cloud.githubusercontent.com/assets/2914096/8633918/9e4ab36c-27e3-11e5-8734-b5ac1fba3cdf.png)

If you face this problem only in special cases, please add a more detailed description, so the failure could be reproduced. Thank you. 

Since I could not reproduce this failure, I am going to close the issue now.

**Closed by BujakiAttila** 2015-07-11 13:44 UTC
