### ISSUE TITLE
Forms - Generating HTML from Java definitions

### ISSUE THREAD

**Issue by JonasGroeger** [JOBAA/amos-ss15-proj4#76] opened 2015-06-20 22:42 UTC
I have decided to currently **not implement the solution of generating the HTML from Java**. The main reason is that **we don't need it right now and probably won't need that until the end of the semester** / for demo day.

Yes its a pain right now. However, its also kind of easy to fix later on. However, I would rather chip away some features right now.

Also, its probably beyond the scope of this project, since its just few weeks ahead. If this project will be an actual product for customers that have needs to change forms every so often, this might be a valid solution.

For reference, here are some nice libraries for doing just that

1. Rendersnake (https://github.com/emicklei/rendersnake): Generate HTML from Java programmatically
2. jpaperwork (https://code.google.com/p/jpaperwork/): Solution for rendering form data to HTML and parsing request parameters back into forms.
3. j2html (http://j2html.com/): Java 8 HTML5 builder, similar to Rendersnake
3. Custom solution. For starters, there is a somewhat working solution for rendering the forms [there](https://github.com/JonasGroeger/html-gen).

So far, solution 2 seems to be the most complete as of yet. However, it has currently no built-in feature to support the Thymeleaf attribute prefix `th:`. This might have to be added to the jpaperwork library.

Any comments?

**Comment by Legend-Dale** [comment] 2015-06-21 10:53
If you say it's currently not worth generating the html then let's hard code it. 
I think it wouldn't have reduced the work much anyway.
We still have to add every field in message_de, message_en, Employee, dashboard, pdf-print, and the html generation class. 

What we could do, however, is to outsource some of the common code of emplyee/form and employee/edit. 

Maybe it could be done with the same html page but two different controllers.
The main difference is, that employee/form redirects to employee/preview and doesn't save the data into the database. 
Employee/edit redirects to client/dashboard and saves the data in the database.

**Comment by JonasGroeger** [comment] 2015-06-21 11:05
> Maybe it could be done with the same html page but two different controllers The main difference is, that employee/form redirects to employee/preview and doesn't save the data into the database.

That could be done. The differences in the form are essentially
* The `action` attribute of the `form` tag.
* The buttons on the bottom
* The readonly flag for all the input elements

So the difference is not just in the behaviour but also in the HTML. To do this, we essentially need three more variables for each of the bulletpoints above

* Model variable for the `action` string.
* Model variable for the String that contains the buttons (not really nice)
* Model variable for the readonly flags. This essentially also means that the edit form will have `readonly="false"` in its HTML.

**Comment by Legend-Dale** [comment] 2015-06-21 12:36
I have deleted employee/form. The behaviour is handles by employee/edit now. 

employee/preview still exists. I would find it nicer if the output would look like the current PDF output. 
Can the respective function be reused for that? (currently it is reading the data from the database...)

**Comment by BujakiAttila** [comment] 2015-07-11 13:48
Instead of using framework/library backed solution now the Employee edit form HTML is generated based on the Employee class definition, using the Reflection API and annotations. For now this solution works well, and was not complicated to introduce.

In the future we could consider using some library or framework instead, but since the issue is solved for now, I am going to close it.

**Closed by BujakiAttila** 2015-07-11 13:48 UTC
